# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fc979fc2efaf349029c65b81d855b7d4017fc273e40e3c02dc70a4461eedbe15e113d9243513f986a068fbe4c8d83a0dbcfd33bb54ba8ed0883c93eea361dbf

test:
  secret_key_base: fd3ac4454e34e691d3322e915629f726610d6d77953dde77251e87614556a9ef2090fbdf38b8c1b0cfd21b4940826c749e549204ff2895fb9072fe391379ac58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
